# See: https://github.com/drone/drone/blob/v0.4.0/docs/build/README.md

debug: true

compose:
  cache:
    image: redis
build:
  tests:
    image: balser/go-buildbox:1.5
    environment:
      - GOROOT=/usr/local/go
      - GOPATH=/drone
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/drone/bin:/usr/local/go/bin
    commands:
      - yum install -y redis
      - make test
    when:
      event: "!tag"
  deploy:
    image: balser/go-buildbox:1.5
    environment:
      - GOROOT=/usr/local/go
      - GOPATH=/drone
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/drone/bin:/usr/local/go/bin
      - INFRA_REPO=$$NP_INFRA_REPO
      - SCRIPT_LOCATION=$$NP_SCRIPT_LOCATION
      - NP_PATH=$$NP_PATH_VALUE
      - PACKER_VPC_ID=$$NP_PACKER_VPC_ID
      - PACKER_SUBNET_ID=$$NP_PACKER_SUBNET_ID
      - S3_VARS_BUCKET=$$NP_S3_VARS_BUCKET
      - S3_STATE_BUCKET=$$NP_S3_STATE_BUCKET
      - AWS_DEFAULT_REGION=$$NP_AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID=$$NP_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$$NP_AWS_SECRET_ACCESS_KEY
      - GITHUB_TOKEN=$$NP_GITHUB_TOKEN
    commands:
      - git clone --depth=1 https://$GITHUB_TOKEN@github.com/$INFRA_REPO.git $NP_PATH
      - curl https://$GITHUB_TOKEN@raw.githubusercontent.com/$SCRIPT_LOCATION > /tmp/np
      - /usr/bin/python /tmp/np build transcoding-api:dev#$${COMMIT:0:7};/usr/bin/python /tmp/np deploy transcoding-api:dev#$${COMMIT:0:7}
    when:
      branch: master
      event: push
  make_live:
    image: balser/go-buildbox:1.5
    environment:
      - INFRA_REPO=$$NP_INFRA_REPO
      - SCRIPT_LOCATION=$$NP_SCRIPT_LOCATION
      - NP_PATH=$$NP_PATH_VALUE
      - PACKER_VPC_ID=$$NP_PACKER_VPC_ID
      - PACKER_SUBNET_ID=$$NP_PACKER_SUBNET_ID
      - S3_VARS_BUCKET=$$NP_S3_VARS_BUCKET
      - S3_STATE_BUCKET=$$NP_S3_STATE_BUCKET
      - AWS_DEFAULT_REGION=$$NP_AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID=$$NP_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$$NP_AWS_SECRET_ACCESS_KEY
      - GITHUB_TOKEN=$$NP_GITHUB_TOKEN
    commands:
      - git clone --depth=1 https://$GITHUB_TOKEN@github.com/$INFRA_REPO.git $NP_PATH
      - curl https://$GITHUB_TOKEN@raw.githubusercontent.com/$SCRIPT_LOCATION > /tmp/np
      - /usr/bin/python /tmp/np deploy transcoding-api:stg#$${COMMIT:0:7};/usr/bin/python /tmp/np deploy transcoding-api:prd#$${COMMIT:0:7}
    when:
      event: tag
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: $$SLACK_USERNAME
    channel: $$SLACK_CHANNEL
