language: go
sudo: false
install: make testdeps
script: make swagger coverage
after_success: bash <(curl -s https://codecov.io/bash)
addons:
  apt:
    packages:
      - redis-server
go:
  - 1.7.3
  - tip
services:
  - redis-server
